name: build_test
on:
  push:
    branches:
      - main
      - dev
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: basic event
        run: echo "initial basic"