name: build_test
on:
  push:
    branches:
      - main
      - dev
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: start build
        run: echo "staarting build"
      - name: get code 
        uses: actions/checkout@v4
      - name: python action setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - name: installing dependency
        run: pip install -r requirements.txt
      - run: python main.py
      - name: build whl file
        run: python setup.py sdist bdist_wheel
      - run: ls /dist