name: build_test
on:
  push:
    branches:
      - main
      - dev
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: start build
        run: echo "staarting build"
      - name: get code 
        uses: actions/checkout@v4
      - name: python action setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - name: installing dependency
        run: |
          pip install -r requirements.txt
          pip install wheel
      - run: python main.py
      - name: build whl file
        run: python setup.py sdist bdist_wheel
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: |
            dist/*
            build/*
      - run: echo "bye bye ...."
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: start build
        run: echo "staarting build"
      - name: get code 
        uses: actions/checkout@v4
      - run: echo "deployment jobs"